### ISSUE TITLE
Catboost incompatible with newest numpy version

### ISSUE THREAD

**Issue by Tole-k** [Tole-k/quick-ai#29]
Catboost library doesn't seem to be compatible with the numpy>=2.0 and we have numpy==2.0.1 specified in the requrements, do we need numpy 2.0.1 for anything?

**Comment by Dawid64** [comment]
Numpy will probably appear in almost every other library that we will use, so I think it's better option to keep it up to date, version 2.0 it's still relatively new, so hopefully catboost package will migrate soon (as far as I know they are working on it). I think it would be the best to disable it until they release the new version, or make the import of it dependent on numpy version

**Comment by Tole-k** [comment]
catboost has already been disabled and there is nothing more we can do for now so closing
